### ISSUE TITLE
Bloop support

### ISSUE THREAD

**Issue by Arthurm1** [sbt/sbt-jupiter-interface#37]
I would like to use your library with [Bloop](https://github.com/scalacenter/bloop) to run unit tests.

Bloop uses virtually the same code as SBT to identify unit tests but it doesn't have the concept of plugins.

I see that you have special code in the SBT plugin to handle test discovery and IIUC it's because SBT only checks _public_ classes for tests and not _package private_ classes

If this restriction is removed, could the test discovery code be moved out of the plugin and into the library so that it would work with Bloop or have I misunderstood the issue?

I've raised an issue here...
scalacenter/bloop#996

**Comment by maichler** [comment]
Hi Arthurm1,

by library code do you mean the library part of this project ? 

If so, please have a look at [JupiterPlugin#L100](https://github.com/maichler/sbt-jupiter-interface/blob/master/src/plugin/src/main/scala/net/aichler/jupiter/sbt/JupiterPlugin.scala#L100]). This is where the plugin uses [JupiterTestCollector](https://github.com/maichler/sbt-jupiter-interface/blob/master/src/library/src/main/java/net/aichler/jupiter/api/JupiterTestCollector.java#L52) from the library code to collect test cases. The plugin code itself doesn't do much except hook into SBT's `definedTests` task.
