### ISSUE TITLE
Preparing for bintray end of service

### ISSUE THREAD

**Issue by mausamyede** [sbt/sbt-jupiter-interface#45]
Hi,

As per recent announcement made by jfrog (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/#:~:text=On%20May%201%2C%202021%2C%20the,to%20use%20the%20Bintray%20service), post 31st March 2021, JCenter will not accept further submissions and JCenter will no longer be available for non-Artifactory clients after 1st Feb 2022.

Are there any plans for publishing this library to other canonical repository like maven central?

**Comment by maichler** [comment]
Hi,

I wasn't aware of the situation, thank you for bringing this  to my attention! I've started the registration process at Sonatype.

**Comment by Mithrandir0x** [comment]
Any updates regarding the registration process?

**Comment by maichler** [comment]
Yes, thanks for asking!

Registration process was successful ([Sonatype Issue](https://issues.sonatype.org/browse/OSSRH-65009) for reference). I did publish versions `0.9.0` and `0.9.1` via `sonatype`, so it should be resolvable through `maven central`.

**Comment by Mithrandir0x** [comment]
Thanks for the effort. I've changed both repository and interface's version without any visible issue and worked like a charm.

**Comment by Dunemaster** [comment]
hello. @maichler 
would you be so kind to update Readme.md as well?

**Comment by maichler** [comment]
Hey @Dunemaster,

thanks for reminding me! 

Did you have something like https://github.com/sbt/sbt-jupiter-interface/pull/51 in mind?

**Comment by Dunemaster** [comment]
@maichler , yes thank

but I also suggest removing  ` resolvers += Resolver.jcenterRepo` from Readme altogether, I just does not work now

**Comment by maichler** [comment]
Oh, I see, good point! I've updated #51 if you want to have another look.

**Comment by Dunemaster** [comment]
Looks good to me, thank you!

**Comment by maichler** [comment]
Closed with #51
