### ISSUE TITLE
Think about migrating to the sbt-organization

### ISSUE THREAD

**Issue by domdorn** [sbt/sbt-jupiter-interface#46]
As your plugin is the defacto standard for sbt-junit5, please think about if you want to migrate it to the sbt organization. 
github.com/sbt/junit5-interface would be a fitting name (IMHO). 

please see this issue for reference: https://github.com/sbt/junit-interface/issues/75
This is written on the offical sbt page (https://www.scala-sbt.org/1.x/docs/Community-Plugins.html) 

> The sbt organization is available for use by any sbt plugin. Developers who contribute their plugins into the community organization will still retain control over their repository and its access. The goal of the sbt organization is to organize sbt software into one central location.

**Comment by maichler** [comment]
Hi and thank you for bringing this to my attention!

If it helps, I'll gladly do this. I'm not sure what's exactly involved, though. Is it just about requesting the project to be moved to `github.com/sbt/` ? The documentation seems a bit dated with its references to `bintray` !?

**Comment by eed3si9n** [comment]
If you could transfer the repo to me, I can transfer it to sbt orgazation and then create a team with you in it who would own the repo.

**Comment by maichler** [comment]
Great! Transfer has been initiated.

**Comment by eed3si9n** [comment]
Thanks. The transfer is complete, and I've invited you to https://github.com/orgs/sbt/teams/junit5-interface-team, which has full rights on this repo.
