### ISSUE TITLE
Migrate groupId to 'com.github.sbt'

### ISSUE THREAD

**Issue by maichler** [sbt/sbt-jupiter-interface#64]
Because this repository already lives under the GitHub sbt organization and also in preparation for an automatic release process from CI via tagging.

/cc @mkurz

**Comment by mkurz** [comment]
Making Scala Steward aware:

- https://github.com/scala-steward-org/scala-steward/pull/3311
- https://github.com/VirtusLab/scala-steward-repos/pull/356
