### ISSUE TITLE
Setup automatic release process

### ISSUE THREAD

**Issue by maichler** [sbt/sbt-jupiter-interface#65]
Set up an automatic release process via GitHub actions so with just pushing a tag a release gets published to maven central automatically.

### Tasks

- [ ] Add release workflow
- [ ] Configure tag protection rules in GitHub

/cc @mkurz

**Comment by maichler** [comment]
It's probably better to change the format of version tags to have a prefix (e.g. `v0.11.1`), since it would simplify things like matching rules, ...

**Comment by maichler** [comment]
> I've just set the Sonatype credential on this repo. You can follow the rest of the instruction from https://github.com/sbt/sbt-ci-release.

That was lightning fast, thank you :+1:

**Comment by mkurz** [comment]
@eed3si9n @maichler Would you mind making me admin of this repo? (So I can add the gpg credentials and maybe set up other stuff)?
